#********************************************************************
# $desc: Makefile for apl-library.info
#********************************************************************

apl-library.info : *.texi
	makeinfo apl-library.texi
